<?php

/**
 * @file
 * Contains dolebas_default_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme()
 * @return mixed
 */
function dolebas_default_content_theme() {

  $theme['dolebas_site_branding_block'] = array(
    'variables' => array(
      'my_variable' => NULL,
    ),
    'template' => 'dolebas_site_branding_block',
  );

  $theme['dolebas_footer_block'] = array(
    'variables' => array(
      'my_variable' => NULL
    ),
    'template' => 'dolebas_footer_block',
  );

  $theme['dolebas_default_content_block'] = array(
    'variables' => array(
      'dolebas_me_view' => NULL,
      'frontpage_player_block' => NULL,
      'dolebas_videoplayer' => NULL
    ),
    'template' => 'dolebas_default_content_block',
  );

  $theme['dolebas_sidebar_menu_block'] = array(
    'variables' => array(
      'my_var' => NULL
    ),
    'template' => 'dolebas_sidebar_menu_block',
  );

  $theme['dolebas_top_bar_block'] = array(
    'variables' => array(
      'dolebas_sidebar_menu_block' => NULL,
      'dolebas_site_branding_block' => NULL,
      'dolebas_user_display_block' => NULL,
    ),
    'template' => 'dolebas_top_bar_block',
  );

  return $theme;

}